language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.2.0beta1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo luarocks install telescope 0.6.0 --server=http://rocks.moonscript.org
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script: "tsc -f specs/*"
  
after_success:
  - luacov-coveralls -c specs/.luacov

notifications:
  email:
    on_success: change
    on_failure: always
